#!/bin/sh

# chkconfig: 2345 20 80
# description: Description comes here....

# Source function library.
. /lib/lsb/init-functions

start() {
   start-stop-daemon --start --oknodo --exec /cnc &>/dev/null
}

stop() {
    start-stop-daemon --stop --oknodo --quiet --exec /cnc
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       status cnc
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0